services:
  app:
    build:
      context: .
      args:
        SECRET_VAULT_PASSWORD: ${SECRET_VAULT_PASSWORD}
    volumes:
      - database:/app/db
    environment:
      SECRET_VAULT_PASSWORD: ${SECRET_VAULT_PASSWORD}
    restart: unless-stopped

volumes:
  database:
